title: NoSchoolBlog
author: NoSchoolTeam
email: kalierincn@outlook.com
description: 中立最好，学校最坏

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: NoSchoolTeam
  tagline: 反学校的一个组织
  date_format: "%Y-%m-%d %H:%M"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    #twitter: thelehhman
    github:  kalicn
   # linkedIn: in/thelehhman
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-feed
